
# Workflow name
name: "Style Dictionary"

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Build styles
        run: yarn run generate-tokens:transform-figma-tokens && yarn run generate-tokens:style-dictionary
